using Microsoft.EntityFrameworkCore;
using System.Text;
using System.Text.RegularExpressions;
using CsvHelper;
using System.Globalization;
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.UseUrls("http://0.0.0.0:5080");
builder.Services.AddDbContext<AppDb>(o=>o.UseSqlite("Data Source=app.db"));
builder.Services.AddDistributedMemoryCache(); builder.Services.AddSession(o=>{o.Cookie.Name="application.sid";o.Cookie.HttpOnly=true;o.IdleTimeout=TimeSpan.FromMinutes(480);});
var app=builder.Build(); app.UseSession(); Directory.CreateDirectory("maildrop");
using(var s=app.Services.CreateScope()){var db=s.ServiceProvider.GetRequiredService<AppDb>();db.Database.EnsureCreated();if(!db.Settings.Any())await Seed(db);}
bool Dev(HttpContext c)=>app.Environment.IsDevelopment(); async Task<User?> Me(HttpContext c,AppDb db){var id=c.Session.GetInt32("uid");return id.HasValue?await db.Users.FindAsync(id.Value):null;} IResult Unauth()=>Results.Json(new{message="ログインが必要です"},statusCode:401); IResult Bad(string m)=>Results.Json(new{message=m},statusCode:400); string Day()=>TimeZoneInfo.ConvertTimeBySystemTimeZoneId(DateTime.UtcNow,"Tokyo Standard Time").ToString("yyyyMMdd"); string Disp(DateTime? d)=>d.HasValue?TimeZoneInfo.ConvertTimeBySystemTimeZoneId(d.Value.ToUniversalTime(),"Tokyo Standard Time").ToString("yyyy/MM/dd HH:mm"):"";
async Task Mail(string to,string subject,string body){var x=new{to,subject,body,sentAt=DateTimeOffset.UtcNow.ToString("O")};await File.WriteAllTextAsync(Path.Combine("maildrop",$"{DateTime.UtcNow:yyyyMMddHHmmssfff}_{Guid.NewGuid():N}.json"),System.Text.Json.JsonSerializer.Serialize(x,new System.Text.Json.JsonSerializerOptions{WriteIndented=true}));}
app.MapPost("/api/dev/reset",async(AppDb db,HttpContext c)=>{if(!Dev(c))return Results.NotFound();db.History.RemoveRange(db.History);db.Applications.RemoveRange(db.Applications);db.Users.RemoveRange(db.Users);db.Settings.RemoveRange(db.Settings);await db.SaveChangesAsync();await Seed(db);foreach(var f in Directory.EnumerateFiles("maildrop"))File.Delete(f);return Results.Ok(new{message="初期化しました"});});
app.MapGet("/api/auth/me",async(AppDb db,HttpContext c)=>{var u=await Me(c,db);return u is null?Unauth():Results.Ok(new{id=u.Id,name=u.Name,email=u.Email,department=u.Department,role=u.Role});});
app.MapPost("/api/auth/login",async(LoginDto x,AppDb db,HttpContext c)=>{var u=await db.Users.SingleOrDefaultAsync(v=>v.Email==x.Email);if(u is null||!u.IsActive||u.Locked)return Results.Json(new{message=u?.Locked==true?"アカウントがロックされています。管理者にお問い合わせください":u?.IsActive==false?"このアカウントは無効です":"メールアドレスまたはパスワードが正しくありません"},statusCode:401);if(!BCrypt.Net.BCrypt.Verify(x.Password,u.PasswordHash)){u.FailedLogins++;if(u.FailedLogins>=5)u.Locked=true;await db.SaveChangesAsync();return Results.Json(new{message=u.Locked?"アカウントがロックされています。管理者にお問い合わせください":"メールアドレスまたはパスワードが正しくありません"},statusCode:401);}u.FailedLogins=0;u.LastLoginAt=DateTime.UtcNow;await db.SaveChangesAsync();c.Session.SetInt32("uid",u.Id);return Results.Ok(new{id=u.Id,name=u.Name,email=u.Email,department=u.Department,role=u.Role});});
app.MapPost("/api/auth/logout",(HttpContext c)=>{c.Session.Clear();return Results.Ok(new{message="ログアウトしました"});});
app.MapPost("/api/auth/register",async(RegisterDto x,AppDb db)=>{var e=VU(x.Name,x.Email,x.Password,x.Department,x.Role);if(e!=null)return Bad(e);if(x.Password!=x.ConfirmPassword)return Bad("パスワードが一致しません");if(await db.Users.AnyAsync(u=>u.Email==x.Email))return Bad("このメールアドレスは既に登録されています");var u=new User{Name=x.Name,Email=x.Email,Department=x.Department,Role=x.Role,PasswordHash=BCrypt.Net.BCrypt.HashPassword(x.Password)};db.Users.Add(u);await db.SaveChangesAsync();await Mail(u.Email,"登録完了のお知らせ",$"{u.Name}様\nアカウント登録が完了しました。");return Results.Ok(new{message="登録が完了しました"});});
app.MapGet("/api/application-types",()=>Results.Ok(new[]{"経費申請","購買申請","その他"}));
app.MapGet("/api/applications",async(HttpContext c,AppDb db,string? keyword,string? status,string? type,string? from,string? to,int? minAmount,int? maxAmount,int page=1)=>{var u=await Me(c,db);if(u is null)return Unauth();var q=db.Applications.Include(a=>a.Applicant).Include(a=>a.Approver).AsQueryable();if(u.Role=="一般")q=q.Where(a=>a.ApplicantId==u.Id);else if(u.Role is "課長" or "部長")q=q.Where(a=>a.ApplicantId==u.Id||a.ApproverId==u.Id);if(!string.IsNullOrWhiteSpace(keyword))q=q.Where(a=>a.Number!.Contains(keyword)||a.Title.Contains(keyword));if(!string.IsNullOrWhiteSpace(status)&&status!="全て")q=q.Where(a=>a.Status==status);if(!string.IsNullOrWhiteSpace(type))q=q.Where(a=>a.Type==type);if(DateTime.TryParse(from,out var fd))q=q.Where(a=>a.ApplicationDate>=fd);if(DateTime.TryParse(to,out var td))q=q.Where(a=>a.ApplicationDate<=td);if(minAmount.HasValue)q=q.Where(a=>a.Amount>=minAmount);if(maxAmount.HasValue)q=q.Where(a=>a.Amount<=maxAmount);var total=await q.CountAsync();var items=await q.OrderByDescending(a=>a.ApplicationDate).Skip((page-1)*20).Take(20).Select(a=>new{a.Id,a.Number,a.Type,a.Title,a.Amount,a.Status,a.ApplicationDate,applicantName=a.Applicant!.Name,approverName=a.Approver==null?"未設定":a.Approver.Name}).ToListAsync();return Results.Ok(new{total,page,items});});
app.MapGet("/api/applications/{id:int}",async(int id,HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u is null)return Unauth();var a=await db.Applications.Include(x=>x.Applicant).Include(x=>x.Approver).Include(x=>x.History).ThenInclude(h=>h.Actor).SingleOrDefaultAsync(x=>x.Id==id);if(a is null)return Results.NotFound(new{message="指定された申請書が見つかりません"});if(u.Role!="管理者"&&a.ApplicantId!=u.Id&&a.ApproverId!=u.Id)return Results.StatusCode(403);return Results.Ok(new{a.Id,a.Number,a.Type,a.Title,a.Amount,a.Reason,a.ApplicationDate,a.Status,a.ApplicantId,a.ApproverId,applicantName=a.Applicant!.Name,approverName=a.Approver?.Name,history=a.History.OrderBy(h=>h.At).Select(h=>new{h.Action,h.Comment,h.At,actorName=h.Actor!.Name,actorRole=h.Actor.Role})});});
app.MapPost("/api/applications",async(AppDto x,HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u is null)return Unauth();var a=new Application{ApplicantId=u.Id,Type=x.Type,Title=x.Title??"",Amount=x.Amount,Reason=x.Reason??"",ApplicationDate=x.ApplicationDate??DateTime.Today,Status="下書き"};db.Applications.Add(a);await db.SaveChangesAsync();return Results.Ok(new{a.Id,message="下書きを保存しました"});});
app.MapPut("/api/applications/{id:int}",async(int id,AppDto x,HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u is null)return Unauth();var a=await db.Applications.FindAsync(id);if(a is null)return Results.NotFound();if(a.ApplicantId!=u.Id||a.Status is "承認済み" or "取消")return Results.StatusCode(403);a.Type=x.Type;a.Title=x.Title??"";a.Amount=x.Amount;a.Reason=x.Reason??"";a.ApplicationDate=x.ApplicationDate??DateTime.Today;await db.SaveChangesAsync();return Results.Ok(new{message="下書きを保存しました"});});
app.MapPost("/api/applications/{id:int}/submit",async(int id,HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u is null)return Unauth();var a=await db.Applications.FindAsync(id);if(a is null)return Results.NotFound();if(a.ApplicantId!=u.Id)return Results.StatusCode(403);var e=VA(new AppDto(a.Type,a.Title,a.Amount,a.Reason,a.ApplicationDate),true);if(e!=null)return Bad(e);var role=a.Amount<=499999?"課長":"部長";var day=Day();var p=await db.Users.Where(x=>x.Role==role&&x.IsActive&&!x.Locked).OrderBy(x=>x.Id).FirstOrDefaultAsync();if(p is null)return Bad("対象の役職を持つユーザーが存在しません。管理者にお問い合わせください");a.ApproverId=p.Id;a.Status="承認待ち";a.SubmittedAt=DateTime.UtcNow;a.Number=$"REQ-{day}-{(await db.Applications.CountAsync(x=>x.Number!=null&&x.Number.StartsWith($"REQ-{day}"))+1):D4}";db.History.Add(new History{ApplicationId=a.Id,ActorId=u.Id,Action="提出",At=DateTime.UtcNow});await db.SaveChangesAsync();await Mail(p.Email,$"【承認依頼】{a.Title}",$"申請番号: {a.Number}\nタイトル: {a.Title}\nステータス: {a.Status}\n申請詳細URL: /applications/{a.Id}");return Results.Ok(new{message="申請を提出しました",a.Number});});
app.MapPost("/api/applications/{id:int}/approve",async(int id,ActionDto x,HttpContext c,AppDb db)=>await Decide(id,x,c,db,true));app.MapPost("/api/applications/{id:int}/reject",async(int id,ActionDto x,HttpContext c,AppDb db)=>await Decide(id,x,c,db,false));
app.MapPost("/api/applications/{id:int}/cancel",async(int id,ActionDto x,HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u is null)return Unauth();var a=await db.Applications.Include(x=>x.Approver).SingleOrDefaultAsync(x=>x.Id==id);if(a is null||a.ApplicantId!=u.Id)return Results.StatusCode(403);if(a.Status is not("下書き" or "承認待ち" or "差し戻し"))return Bad("承認済みの申請書は取り消しできません");var was=a.Status=="承認待ち";a.Status="取消";db.History.Add(new History{ApplicationId=id,ActorId=u.Id,Action="取り消し",Comment=x.Comment,At=DateTime.UtcNow});await db.SaveChangesAsync();if(was&&a.Approver!=null)await Mail(a.Approver.Email,$"【取り消し】{a.Title}",$"申請番号: {a.Number}\nタイトル: {a.Title}\nステータス: 取消\n申請詳細URL: /applications/{id}");return Results.Ok(new{message="申請を取り消しました"});});
app.MapGet("/api/dashboard",async(HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u is null)return Unauth();var own=db.Applications.Where(a=>a.ApplicantId==u.Id);var recent=await own.OrderByDescending(a=>a.ApplicationDate).Take(5).Select(a=>new{a.Id,a.Number,a.Title,a.Status,a.Amount}).ToListAsync();return Results.Ok(new{counts=new{pending=await own.CountAsync(a=>a.Status=="承認待ち"),approved=await own.CountAsync(a=>a.Status=="承認済み"),returned=await own.CountAsync(a=>a.Status=="差し戻し"),approvalPending=u.Role is "課長" or "部長"?await db.Applications.CountAsync(a=>a.ApproverId==u.Id&&a.Status=="承認待ち"):0},recent,userCount=u.Role=="管理者"?await db.Users.CountAsync():0,totalApplications=u.Role=="管理者"?await db.Applications.CountAsync():0});});
app.MapGet("/api/users",async(HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u?.Role!="管理者")return Results.StatusCode(403);return Results.Ok(await db.Users.Select(x=>new{x.Id,x.Name,x.Email,x.Department,x.Role,x.IsActive,x.Locked}).ToListAsync());});
app.MapPut("/api/users/{id:int}",async(int id,UserUpdateDto x,HttpContext c,AppDb db)=>{var me=await Me(c,db);if(me?.Role!="管理者")return Results.StatusCode(403);if(id==me.Id&&!x.IsActive)return Bad("自分自身のアカウントを無効にすることはできません");var u=await db.Users.FindAsync(id);if(u is null)return Results.NotFound();if(await db.Users.AnyAsync(z=>z.Email==x.Email&&z.Id!=id))return Bad("このメールアドレスは既に使用されています");u.Name=x.Name;u.Email=x.Email;u.Department=x.Department;u.Role=x.Role;u.IsActive=x.IsActive;await db.SaveChangesAsync();return Results.Ok(new{message="ユーザー情報を更新しました"});});
app.MapPost("/api/account/password",async(PasswordDto x,HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u is null)return Unauth();if(!BCrypt.Net.BCrypt.Verify(x.CurrentPassword,u.PasswordHash))return Bad("現在のパスワードが正しくありません");if(x.NewPassword!=x.ConfirmPassword)return Bad("新しいパスワードが一致しません");if(!Strong(x.NewPassword))return Bad("パスワードは8文字以上で英字と数字を含めてください");if(x.CurrentPassword==x.NewPassword)return Bad("新しいパスワードは現在のパスワードと異なるものを設定してください");u.PasswordHash=BCrypt.Net.BCrypt.HashPassword(x.NewPassword);await db.SaveChangesAsync();c.Session.Clear();return Results.Ok(new{message="パスワードを変更しました。再度ログインしてください"});});
app.MapGet("/api/settings",async(HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u?.Role!="管理者")return Results.StatusCode(403);return Results.Ok(await db.Settings.FirstAsync());});
app.MapPut("/api/settings",async(SettingsDto x,HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u?.Role!="管理者")return Results.StatusCode(403);var s=await db.Settings.FirstAsync();if(x.Port is <1 or >65535||x.LockThreshold is <1 or >10||x.TimeoutMinutes is <5 or >480)return Bad("設定値の値が不正です");s.SmtpHost=x.SmtpHost;s.SmtpPort=x.Port;s.SmtpUser=x.SmtpUser;s.FromEmail=x.FromEmail;s.LockThreshold=x.LockThreshold;s.TimeoutMinutes=x.TimeoutMinutes;await db.SaveChangesAsync();return Results.Ok(new{message="システム設定を保存しました"});});
app.MapPost("/api/settings/test",async(HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u?.Role!="管理者")return Results.StatusCode(403);var s=await db.Settings.FirstAsync();await Mail(s.FromEmail,"SMTPテスト送信","SMTP設定のテスト送信です。");return Results.Ok(new{message="テスト送信に成功しました"});});
app.MapGet("/api/applications/export",async(HttpContext c,AppDb db)=>{var u=await Me(c,db);if(u is null)return Unauth();if(u.Role is not("管理者" or "課長" or "部長"))return Results.StatusCode(403);var rows=await db.Applications.Include(a=>a.Applicant).Include(a=>a.Approver).OrderByDescending(a=>a.ApplicationDate).Take(10001).ToListAsync();if(rows.Count>10000)return Bad("エクスポート対象が10,000件を超えています。条件を絞り込んでください");using var sw=new StringWriter(CultureInfo.InvariantCulture);using var csv=new CsvWriter(sw,CultureInfo.InvariantCulture);csv.WriteField("申請番号");csv.WriteField("申請種別");csv.WriteField("申請タイトル");csv.WriteField("申請金額");csv.WriteField("ステータス");csv.WriteField("申請者名");csv.WriteField("承認者名");csv.WriteField("申請日");csv.WriteField("承認日");csv.NextRecord();foreach(var a in rows){csv.WriteField(a.Number);csv.WriteField(a.Type);csv.WriteField(a.Title);csv.WriteField(a.Amount);csv.WriteField(a.Status);csv.WriteField(a.Applicant?.Name);csv.WriteField(a.Approver?.Name);csv.WriteField(a.ApplicationDate.ToString("yyyy/MM/dd"));csv.WriteField(a.Status=="承認済み"?(a.UpdatedAt.HasValue?a.UpdatedAt.Value.ToString("yyyy/MM/dd HH:mm"):""):"");csv.NextRecord();}return Results.File(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(sw.ToString())).ToArray(),"text/csv",$"applications_{DateTime.Now:yyyyMMdd_HHmmss}.csv");});
app.Run();
static string? VU(string? n,string? e,string? p,string? d,string? r){if(string.IsNullOrWhiteSpace(n))return "氏名を入力してください";if(n.Length>50)return "氏名は50文字以内で入力してください";if(!Regex.IsMatch(e??"",@"^[^@\s]+@[^@\s]+\.[^@\s]+$"))return "有効なメールアドレスを入力してください";if(!Strong(p))return "パスワードは8文字以上で英字と数字を含めてください";if(string.IsNullOrWhiteSpace(d))return "所属部署を入力してください";if(!new[]{"一般","課長","部長","管理者"}.Contains(r))return "役職を選択してください";return null;} static bool Strong(string? p)=>!string.IsNullOrEmpty(p)&&p.Length>=8&&p.Any(char.IsLetter)&&p.Any(char.IsDigit); static string? VA(AppDto x,bool req)=>req&&string.IsNullOrWhiteSpace(x.Title)?"申請タイトルを入力してください":req&&(x.Amount<1||x.Amount>9999999)?"申請金額は1円以上9,999,999円以下で入力してください":req&&string.IsNullOrWhiteSpace(x.Reason)?"申請理由を入力してください":x.ApplicationDate is null||x.ApplicationDate.Value.Date<DateTime.Today?"申請日は当日以降の日付を入力してください":null;
async Task<IResult> Decide(int id,ActionDto x,HttpContext c,AppDb db,bool ok){var u=await Me(c,db);if(u is null)return Unauth();var a=await db.Applications.Include(z=>z.Applicant).SingleOrDefaultAsync(z=>z.Id==id);if(a is null||a.ApproverId!=u.Id)return Results.StatusCode(403);if(a.Status!="承認待ち")return Bad("承認待ち状態の申請書のみ処理できます");if(!ok&&string.IsNullOrWhiteSpace(x.Comment))return Bad("差し戻し理由を入力してください");a.Status=ok?"承認済み":"差し戻し";a.UpdatedAt=DateTime.UtcNow;db.History.Add(new History{ApplicationId=id,ActorId=u.Id,Action=ok?"承認":"差し戻し",Comment=x.Comment,At=DateTime.UtcNow});await db.SaveChangesAsync();await Mail(a.Applicant!.Email,ok?$"【承認完了】{a.Title}":$"【差し戻し】{a.Title}",$"申請番号: {a.Number}\nタイトル: {a.Title}\nステータス: {a.Status}\n申請詳細URL: /applications/{id}\nコメント: {x.Comment}");return Results.Ok(new{message=ok?"承認しました":"差し戻しました"});}
static async Task Seed(AppDb db){db.Settings.Add(new Settings{SmtpHost="localhost",SmtpPort=25,SmtpUser="smtp-user",FromEmail="admin@example.com",LockThreshold=5,TimeoutMinutes=480});foreach(var x in new[]{("admin@example.com","管理者 太郎","管理部","管理者"),("kacho@example.com","課長 一郎","営業部","課長"),("bucho@example.com","部長 次郎","営業部","部長"),("ippan@example.com","一般 三郎","営業部","一般")})db.Users.Add(new User{Email=x.Item1,Name=x.Item2,Department=x.Item3,Role=x.Item4,PasswordHash=BCrypt.Net.BCrypt.HashPassword("Password1")});await db.SaveChangesAsync();}
record LoginDto(string Email,string Password);record RegisterDto(string Name,string Email,string Password,string ConfirmPassword,string Department,string Role);record AppDto(string Type,string? Title,int Amount,string? Reason,DateTime? ApplicationDate);record ActionDto(string? Comment);record UserUpdateDto(string Name,string Email,string Department,string Role,bool IsActive);record PasswordDto(string CurrentPassword,string NewPassword,string ConfirmPassword);record SettingsDto(string SmtpHost,int Port,string SmtpUser,string FromEmail,int LockThreshold,int TimeoutMinutes);
class User{public int Id{get;set;}public string Name{get;set;}="";public string Email{get;set;}="";public string Department{get;set;}="";public string Role{get;set;}="一般";public string PasswordHash{get;set;}="";public bool IsActive{get;set;}=true;public bool Locked{get;set;}public int FailedLogins{get;set;}public DateTime? LastLoginAt{get;set;}}
class Application{public int Id{get;set;}public string? Number{get;set;}public string Type{get;set;}="";public string Title{get;set;}="";public int Amount{get;set;}public string Reason{get;set;}="";public DateTime ApplicationDate{get;set;}public string Status{get;set;}="下書き";public int ApplicantId{get;set;}public User? Applicant{get;set;}public int? ApproverId{get;set;}public User? Approver{get;set;}public DateTime? SubmittedAt{get;set;}public DateTime? UpdatedAt{get;set;}public List<History> History{get;set;}=new();}
class History{public int Id{get;set;}public int ApplicationId{get;set;}public Application? Application{get;set;}public int ActorId{get;set;}public User? Actor{get;set;}public string Action{get;set;}="";public string? Comment{get;set;}public DateTime At{get;set;}}
class Settings{public int Id{get;set;}public string SmtpHost{get;set;}="";public int SmtpPort{get;set;}public string SmtpUser{get;set;}="";public string FromEmail{get;set;}="";public int LockThreshold{get;set;}public int TimeoutMinutes{get;set;}}
class AppDb:DbContext{public AppDb(DbContextOptions<AppDb> o):base(o){}public DbSet<User> Users=>Set<User>();public DbSet<Application> Applications=>Set<Application>();public DbSet<History> History=>Set<History>();public DbSet<Settings> Settings=>Set<Settings>();protected override void OnModelCreating(ModelBuilder b){b.Entity<User>().HasIndex(x=>x.Email).IsUnique();b.Entity<Application>().HasOne(x=>x.Applicant).WithMany().HasForeignKey(x=>x.ApplicantId).OnDelete(DeleteBehavior.Restrict);b.Entity<Application>().HasOne(x=>x.Approver).WithMany().HasForeignKey(x=>x.ApproverId).OnDelete(DeleteBehavior.Restrict);b.Entity<History>().HasOne(x=>x.Actor).WithMany().HasForeignKey(x=>x.ActorId).OnDelete(DeleteBehavior.Restrict);}}
